### ISSUE TITLE
Created data folders

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/RA2-dream-workflows#3]
I think these are now finalized. 

I spent some time copying data so that we don't have to have so many mount points..it was a little scattered before. 

For leaderboard round:

/input/ volume mount should map to /data/projects/RA2_DREAM/leaderboard_round/

this directory contains `test` and `train` subdirectories. `test` contains leaderboard image data and a submission template named template.csv. `train` contains training image data and a csv of SvH scores named train.csv. 

For final scoring round:

/input/ volume mount should map to /data/projects/RA2_DREAM/final_round/

this directory contains `test` and `train` subdirectories. `test` contains final round image data and a submission template named template.csv. `train` contains training image data and a csv of SvH scores named train.csv.

**Comment by allaway** [comment]
Chatted with @thomasyu888 offline, lets do two mount points instead of one.

This means i need to change the instructions slightly here: https://www.synapse.org/#!Synapse:syn20545112/wiki/594091

and to reorganize the data into:

/data/projects/RA2_DREAM/train/ <- same for both rounds, contains images and training csv

and then the test datasets/template csvs will be in: 
/data/projects/RA2_DREAM/test_teaderboard/ 
and
data/projects/RA2_DREAM/test_final/

Sound good?

**Comment by thomasyu888** [comment]
Looks good to me! Will make that mod

**Comment by allaway** [comment]
Great! I just renamed/moved files on UAB as necessary.

**Comment by allaway** [comment]
fixed docs on staging. https://www.synapse.org/#!Synapse:syn20545112/wiki/594091

**Comment by thomasyu888** [comment]
Gonna reopen until I fix in my PR

**Comment by allaway** [comment]
Ah, good call 👍
